<?xml version="1.0" encoding="UTF-8"?>
<definitions name="WeatherProxy" targetNamespace="http://modalis.i3s.unice.fr/jSeduite/wsdl/WeatherProxy"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://modalis.i3s.unice.fr/jSeduite/wsdl/WeatherProxy" xmlns:ns="http://modalis.i3s.unice.fr/jSeduite/schema/WeatherProxy" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://modalis.i3s.unice.fr/jSeduite/wsdl/WeatherProxy">
            <xsd:import namespace="http://modalis.i3s.unice.fr/jSeduite/schema/WeatherProxy" schemaLocation="WeatherProxy.xsd"/>
        </xsd:schema>
    </types>
    <message name="WeatherProxyOperationRequest">
        <part name="in" element="ns:WeatherProxyRequest"/>
    </message>
    <message name="WeatherProxyOperationResponse">
        <part name="out" element="ns:WeatherProxyResponse"/>
    </message>
    <portType name="WeatherProxyPortType">
        <operation name="WeatherProxyOperation">
            <input name="input1" message="tns:WeatherProxyOperationRequest"/>
            <output name="output1" message="tns:WeatherProxyOperationResponse"/>
        </operation>
    </portType>
    <binding name="WeatherProxyBinding" type="tns:WeatherProxyPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="WeatherProxyOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="WeatherProxyService">
        <port name="WeatherProxyPort" binding="tns:WeatherProxyBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/WeatherProxyService/WeatherProxyPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="WeatherProxy">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="WeatherProxyPortTypeRole" portType="tns:WeatherProxyPortType"/>
    </plnk:partnerLinkType>
</definitions>
