<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PartnerKeysServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/PartnerKeysServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/PartnerKeysServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://partners.registry.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="PartnerKeysService.wsdl" namespace="http://partners.registry.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="PartnerKeysLinkType">
        <plnk:role name="key_registryRole" portType="ns:PartnerKeys"/>
    </plnk:partnerLinkType>
</definitions>
