<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PicasaWrapperServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/PicasaWrapperServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/PicasaWrapperServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://picasa.image.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="PicasaWrapperService.wsdl" namespace="http://picasa.image.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="PicasaWrapperLinkType">
        <plnk:role name="PicasaWrapperRole" portType="ns:PicasaWrapper"/>
    </plnk:partnerLinkType>
</definitions>
