<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="FeedRegistryServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/FeedRegistryServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/FeedRegistryServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://registry.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="FeedRegistryService.wsdl" namespace="http://registry.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="FeedRegistryLinkType">
        <plnk:role name="FeedRegistryRole" portType="ns:FeedRegistry"/>
    </plnk:partnerLinkType>
</definitions>
