<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="RssReaderServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/RssReaderServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/RssReaderServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://feeds.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="RssReaderService.wsdl" namespace="http://feeds.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="RssReaderLinkType">
        <plnk:role name="RssReaderRole" portType="ns:RssReader"/>
    </plnk:partnerLinkType>
</definitions>
