<?xml version="1.0" encoding="UTF-8"?>
<definitions name="InfoProvider" targetNamespace="http://modalis.polytech.unice.fr/jSeduite/providers/wsdl/InfoProvider"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://modalis.polytech.unice.fr/jSeduite/providers/wsdl/InfoProvider" xmlns:ns="http://modalis.polytech.unice.fr/jSeduite/providers/schema/InfoProvider" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://modalis.polytech.unice.fr/jSeduite/providers/wsdl/InfoProvider">
            <xsd:import namespace="http://modalis.polytech.unice.fr/jSeduite/providers/schema/InfoProvider" schemaLocation="InfoProvider.xsd"/>
        </xsd:schema>
    </types>
    <message name="GetAllInformationsRequest">
        <part name="in" element="ns:GetAllInformationRequest"/>
    </message>
    <message name="GetAllInformationsResponse">
        <part name="out" element="ns:GetAllInformationResponse"/>
    </message>
    <portType name="InfoProviderPortType">
        <operation name="GetAllInformations">
            <input name="input1" message="tns:GetAllInformationsRequest"/>
            <output name="output1" message="tns:GetAllInformationsResponse"/>
        </operation>
    </portType>
    <binding name="InfoProviderBinding" type="tns:InfoProviderPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="GetAllInformations">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="InfoProviderService">
        <port name="InfoProviderPort" binding="tns:InfoProviderBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/InfoProviderService/InfoProviderPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="InfoProvider">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="provider" portType="tns:InfoProviderPortType"/>
    </plnk:partnerLinkType>
</definitions>
