<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PreferenceManagerServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/PreferenceManagerServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/PreferenceManagerServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://preferences.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="PreferenceManagerService.wsdl" namespace="http://preferences.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="PreferenceManagerLinkType">
        <plnk:role name="preferences" portType="ns:PreferenceManager"/>
    </plnk:partnerLinkType>
</definitions>
