<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="HyperMachinServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/HyperMachinServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/HyperMachinServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://modalis.i3s.unice.fr/jSeduite/ws/technical/hypermachin">
    <import location="HyperMachinService.wsdl" namespace="http://modalis.i3s.unice.fr/jSeduite/ws/technical/hypermachin"/>
    <plnk:partnerLinkType name="HyperMachinLinkType">
        <plnk:role name="HyperMachinRole" portType="ns:HyperMachin"/>
    </plnk:partnerLinkType>
</definitions>
