<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="FlickrWrapperServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/FlickrWrapperServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/FlickrWrapperServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://flickr.image.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="FlickrWrapperService.wsdl" namespace="http://flickr.image.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="FlickrWrapperLinkType">
        <plnk:role name="flickr" portType="ns:FlickrWrapper"/>
    </plnk:partnerLinkType>
</definitions>
