<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="AlarmBusinessServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/AlarmBusinessServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/AlarmBusinessServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://alarms.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="AlarmBusinessService.wsdl" namespace="http://alarms.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="AlarmBusinessLinkType">
        <plnk:role name="AlarmBusinessRole" portType="ns:AlarmBusiness"/>
    </plnk:partnerLinkType>
</definitions>
