<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ApalWrapperServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/ApalWrapperServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/ApalWrapperServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://apal.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="ApalWrapperService.wsdl" namespace="http://apal.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="ApalWrapperLinkType">
        <plnk:role name="ApalWrapperRole" portType="ns:ApalWrapper"/>
    </plnk:partnerLinkType>
</definitions>
