<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="BreakingNewsServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/BreakingNewsServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/BreakingNewsServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://breaking.news.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="BreakingNewsService.wsdl" namespace="http://breaking.news.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="BreakingNewsLinkType">
        <plnk:role name="BreakingNewsRole" portType="ns:BreakingNews"/>
    </plnk:partnerLinkType>
</definitions>
