<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="EphemeridesServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/EphemeridesServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/EphemeridesServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://Ephemerides.time.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="EphemeridesService.wsdl" namespace="http://Ephemerides.time.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="EphemeridesLinkType">
        <plnk:role name="EphemeridesRole" portType="ns:Ephemerides"/>
    </plnk:partnerLinkType>
</definitions>
