<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="HyperLocatorServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/HyperLocatorServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/HyperLocatorServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://modalis.i3s.unice.fr/jSeduite/ws/technical/hyperlocator">
    <import location="HyperLocatorService.wsdl" namespace="http://modalis.i3s.unice.fr/jSeduite/ws/technical/hyperlocator"/>
    <plnk:partnerLinkType name="HyperLocatorLinkType">
        <plnk:role name="HyperLocatorRole" portType="ns:HyperLocator"/>
    </plnk:partnerLinkType>
</definitions>
