<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ICalReaderServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/ICalReaderServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/ICalReaderServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://calendar.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="ICalReaderService.wsdl" namespace="http://calendar.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="ICalReaderLinkType">
        <plnk:role name="ICalReaderRole" portType="ns:ICalReader"/>
    </plnk:partnerLinkType>
</definitions>
