<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="MenuBusinessServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/MenuBusinessServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/MenuBusinessServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://restaurant.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="MenuBusinessService.wsdl" namespace="http://restaurant.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="MenuBusinessLinkType">
        <plnk:role name="MenuBusinessRole" portType="ns:MenuBusiness"/>
    </plnk:partnerLinkType>
</definitions>
