<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PictogramBusinessServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/PictogramBusinessServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/PictogramBusinessServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://pictogram.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="PictogramBusinessService.wsdl" namespace="http://pictogram.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="PictogramBusinessLinkType">
        <plnk:role name="PictogramBusinessRole" portType="ns:PictogramBusiness"/>
    </plnk:partnerLinkType>
</definitions>
