<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="StudentSummonServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/StudentSummonServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/StudentSummonServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://summon.news.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="StudentSummonService.wsdl" namespace="http://summon.news.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="StudentSummonLinkType">
        <plnk:role name="StudentSummonRole" portType="ns:StudentSummon"/>
    </plnk:partnerLinkType>
</definitions>
