<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="TeacherAbsencesServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/TeacherAbsencesServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/TeacherAbsencesServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://absence.news.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="TeacherAbsencesService.wsdl" namespace="http://absence.news.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="TeacherAbsencesLinkType">
        <plnk:role name="TeacherAbsencesRole" portType="ns:TeacherAbsences"/>
    </plnk:partnerLinkType>
</definitions>
