<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="TwitterWrapperServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/TwitterWrapperServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/TwitterWrapperServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://twitter.messaging.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="TwitterWrapperService.wsdl" namespace="http://twitter.messaging.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="TwitterWrapperLinkType">
        <plnk:role name="TwitterWrapperRole" portType="ns:TwitterWrapper"/>
    </plnk:partnerLinkType>
</definitions>
