<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="TvHelperServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/TvHelperServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/TvHelperServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://tv.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="TvHelperService.wsdl" namespace="http://tv.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="TvHelperLinkType">
        <plnk:role name="TvHelperRole" portType="ns:TvHelper"/>
    </plnk:partnerLinkType>
</definitions>
