<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="AccountManagerServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/AccountManagerServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/AccountManagerServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://accounts.technical.jSeduite.modalis.i3s.unice.fr/">
    <import location="AccountManagerService.wsdl" namespace="http://accounts.technical.jSeduite.modalis.i3s.unice.fr/"/>
    <plnk:partnerLinkType name="AccountManagerLinkType">
        <plnk:role name="accounts" portType="ns:AccountManager"/>
    </plnk:partnerLinkType>
</definitions>
